- name: copy 
  synchronize:
    src: "{{ src_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
        - "--exclude=node_modules"
        - "--exclude=SAtest_iac"
        - "--exclude=.git"
        - "--exclude=.gitignore"
        - "--exclude=README.md"
        - "--exclude=SAtest_iac@tmp"
        - "--exclude=ssh*"
  tags:
    - copy_files